nelmio_api_doc:
    documentation:
        host: localhost
        schemes: [http]
        info:
            title: My App
            description: This is an awesome app!
            version: '0.6.1'
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api).*$) # Accepts routes under /api except /api/doc
