nelmio_api_doc:
    documentation:
        host: localhost
        schemes: [http]
        info:
            title: Documentation API Characters
            description: C'est vraiment la meilleure API !
            version: '0.6.1'
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api).*$) # Accepts routes under /api except /api/doc
